Extended docker and docker-compose
However, ERROR resolution is required..
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure